services:

  standalone:
    container_name: standalone
    image: ghcr.io/opencoremmo/opencoremmo:baiak
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      SQLITE_DATABASE: "${SQLITE_DATABASE}"
      POSTGRESQL_DATABASE: "${POSTGRESQL_DATABASE}"
      POSTGRESQL_USER: "${POSTGRESQL_USER}"
      POSTGRESQL_PASSWORD: "${POSTGRESQL_PASSWORD}"
      POSTGRESQL_HOST: "${POSTGRESQL_HOST}"
      POSTGRESQL_PORT: "${POSTGRESQL_PORT}"
      ACTIVE_DATABASE: "${ACTIVE_DATABASE}"
      SERVER_LOGIN_PORT: "${SERVER_LOGIN_PORT}"
      SERVER_GAME_PORT: "${SERVER_GAME_PORT}"
      SERVER_GAME_NAME: "${SERVER_GAME_NAME}"
      SERVER_GAME_IP: "${SERVER_GAME_IP}"
      GRAYLOG_HOSTNAME_OR_ADDRESS: "${GRAYLOG_HOSTNAME_OR_ADDRESS}"
      GRAYLOG_PORT: "${GRAYLOG_PORT}"
      GRAYLOG_HOSTNAME_OVERRIDE: "${GRAYLOG_HOSTNAME_OVERRIDE}"
      GRAYLOG_FACILITY: "${GRAYLOG_FACILITY_STANDALONE}"
    ports:
      - "${SERVER_LOGIN_PORT}:${SERVER_LOGIN_PORT}"
      - "${SERVER_GAME_PORT}:${SERVER_GAME_PORT}"
    volumes:
      - data:/app/data
    restart: "on-failure"
    networks:
      - opencoremmo

networks:
  opencoremmo:
    external: true

volumes:
  data:
    driver: local