services:
# PostgreSQL: https://hub.docker.com/_/postgres/
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "${POSTGRESQL_PASSWORD}"
      POSTGRES_USER: "${POSTGRESQL_USER}"
      POSTGRES_DB: "${POSTGRESQL_DATABASE}"
    ports:
      - "${POSTGRESQL_PORT}:${POSTGRESQL_PORT}"
    restart: "on-failure"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - opencoremmo

# OpenCoreMMO
  standalone:
    container_name: standalone
    build:
      context: .
      dockerfile: ./src/Standalone/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      DOCKER: true
    ports:
      - "${SERVER_LOGIN_PORT}:${SERVER_LOGIN_PORT}"
      - "${SERVER_GAME_PORT}:${SERVER_GAME_PORT}"
    restart: "on-failure"
    networks:
      - opencoremmo
    depends_on:
      - postgres

  # webapi-compose:
  #   container_name: webapi
  #   build:
  #     context: ./src/WebAPI/
  #     dockerfile: Dockerfile
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: "Production"
  #   ports:
  #     - "80:80"
  #   networks:
  #     - opencoremmo

networks: 
  opencoremmo:
    driver: bridge

volumes:
  postgresql-data:
