<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Common\Spell\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Serilog" Version="4.3.1" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Common\Contracts\World\IMapService.cs" />
      <Compile Remove="World\Services\MapService.cs" />
    </ItemGroup>
</Project>
