<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Common\Spell\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Serilog" Version="4.4.0" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Common\Contracts\World\IMapService.cs" />
      <Compile Remove="World\Services\MapService.cs" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>NeoServer.Domain.Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>
</Project>
