namespace NeoServer.Scripts.LuaJIT.Models.Combat;

public enum CombatParam
{
    COMBAT_PARAM_TYPE,
    COMBAT_PARAM_EFFECT,
    COMBAT_PARAM_DISTANCEEFFECT,
    COMBAT_PARAM_BLOCKSHIELD,
    COMBAT_PARAM_BLOCKARMOR,
    COMBAT_PARAM_TARGETCASTERORTOPMOST,
    COMBAT_PARAM_CREATEITEM,
    COMBAT_PARAM_AGGRESSIVE,
    COMBAT_PARAM_DISPEL,
    COMBAT_PARAM_USECHARGES,
    COMBAT_PARAM_CASTSOUND,
    COMBAT_PARAM_IMPACTSOUND,
    COMBAT_PARAM_CHAIN_EFFECT,
}