namespace NeoServer.Scripts.LuaJIT.Models.Combat;

public enum CombatType
{
    COMBAT_PHYSICALDAMAGE = 0,
    COMBAT_ENERGYDAMAGE = 1,
    COMBAT_EARTHDAMAGE = 2,
    COMBAT_FIREDAMAGE = 3,
    COMBAT_UNDEFINEDDAMAGE = 4,
    COMBAT_LIFEDRAIN = 5,
    COMBAT_MANADRAIN = 6,
    COMBAT_HEALING = 7,
    COMBAT_DROWNDAMAGE = 8,
    COMBAT_ICEDAMAGE = 9,
    COMBAT_HOLYDAMAGE = 10,
    COMBAT_DEATHDAMAGE = 11,
    COMBAT_AGONYDAMAGE = 12,
    COMBAT_NEUTRALDAMAGE = 13,

    COMBAT_COUNT = 14,

    // Server read only
    COMBAT_NONE = 255
}