namespace NeoServer.Domain.Common.Item;

public enum ItemAttribute : byte
{
    None = 0,
    ActionId = 1,
    UniqueId = 2,
    Description = 3,
    Text = 4,
    Date = 5,
    Writer = 6,
    Name = 7,
    Article = 8,
    PluralName = 9,
    Weight = 10,
    Attack = 11,
    Defense = 12,
    ExtraDefense = 13,
    Armor = 14,
    HitChance = 15,
    ShootRange = 16,
    Owner = 17,
    Duration = 18,
    DecayState = 19,
    CorpseOwner = 20,
    Charges = 21,
    FluidType = 22,
    DoorId = 23,
    DecayTo = 24,
    WrapId = 25,
    StoreItem = 26,
    AttackSpeed = 27, // todo: Check this, exists in TFS but not in Canary?
    Custom = 28,
    TeleportDestination = 29, // specifics to opencoremmorpg load teleports from map,
    Count = 30 // specifics to opencoremmorpg load count from map
}

public enum ItemTypeAttribute : byte
{
    //ItemParseAttributes
    None = 0,
    StoreItem,
    Text,
    Name,
    Article,
    PluralName,
    Type,
    Description,
    RuneSpellName,
    Weight,
    ShowCount,
    Armor,
    Defense,
    ExtraDefense,
    Attack,
    AttackSpeed,
    RotateTarget,
    Moveable,
    BlockProjectTile,
    Pickupable,
    ForceSerialize,
    FloorChange,
    CorpseType,
    Capacity,
    SourceLiquidType,
    ContainerLiquidType,
    Readable,
    Writeable,
    MaxLength,
    WriteOnceItemId,
    WeaponType,
    BodyPosition,
    AmmoType,
    ShootType,
    Effect,
    Range,
    StopDecaying,
    ExpireTarget,
    TransformEquipTo,
    TransformDequipTo,
    Duration,
    ShowDuration,
    Charges,
    ShowCharges,
    ShowAttributes,
    HitChance,
    MaxHitChance,
    Invisible,
    Speed,
    HealthGain,
    HealTicks,
    ManaGain,
    ManaTicks,
    ManaShield,
    SkillSword,
    SkillAxe,
    SkillClub,
    SkillDistance,
    SkillFishing,
    SkillShield,
    SkillFist,
    MaxHitpoints,
    MaxHitpointsPercent,
    MaxManapoints,
    MaxManaPointsPercent,
    MagicPoints,
    MagicPointsPercent,
    CriticalHitChance,
    CriticalHitAmount,
    LifeLeechChance,
    LifeLeechAmount,
    ManaLeechChange,
    ManaLeechAmout,
    FieldAbsorbPercentEnergy,
    FieldAbsorbEercentFire,
    FieldAbsorbPercentPoison,
    AbsorbPercentAll,
    AbsorbPercentElements,
    AbsorbPercentMagic,
    AbsorbPercentEnergy,
    AbsorbPercentFire,
    AbsorbPercentPoison,
    AbsorbPercentIce,
    AbsorbPercentHoly,
    AbsorbPercentDeath,
    AbsorbPercentLifeDrain,
    AbsorbPercentManaDrain,
    AbsorbPercentDrown,
    AbsorbPercentPhysical,
    AbsorbPercentHealing,
    AbsorbPercentUndefined,
    SuppressDrunk,
    SuppressEnergy,
    SuppressFire,
    SuppressPoison,
    SuppressDrown,
    SuppressPhysical,
    SuppressFreeze,
    SuppressDazzle,
    SuppressCurse,
    Field,
    Replaceable,
    PartnerDirection,
    LevelDoor,
    MaleTransformTo,
    FemaleTransformTo,
    TransformTo,
    DestroyTo,
    ElementIce,
    ElementEarth,
    ElementFire,
    ElementEnergy,
    ElementDeath,
    ElementHoly,
    WalkStack,
    Blocking,
    AllowDistRead,
    MinimumLevel,
    MinimumMagicLevel,
    TeleportDestination,
    UseOn,
    Healing,
    Min,
    Max,
    Sentence,
    Vocation,
    Regeneration,
    NeedTarget,
    Formula,
    Damage,
    Area,
    Ticks,
    Script,
    Worth,
    ManaUse,
    CooldownTime,
    SoulUse,

    //Runes, Weapons, Ammos, Doors and Others
    //todo: Organize these attributes better
    AnotherDescription,
    ExtensionFile,
    TileFlags,
    Item,
    DepotId,
    ExtensionFileForSpawns,
    ExtensionFileForHouses,
    SleeperGuid,
    SleepStart,
    ContainerItems,
    IsAggressive,
    DecayTo,
    DecayElapsed,
    AllowFarUse,
    Count,
    VocationNames,
    DestroyTarget,
    Waypoints,
    CheckFloor,
    BlockWalls,
    NeedDirection,
    CasterNeedsTargetOrDirection,
    SelfTarget,
    NeedWeapon,
    NeedLearn,
    NeedsPremium,
    CooldownId,
    PrimaryGroup,
    PrimaryGroupCooldown,
    SecondaryGroup,
    SecondaryGroupCooldown,
    AbsTeleportEffect,
    AmmoAttackValue,
    AmmoEffectStrength,
    AmmoMissile,
    AmmoSpecialEffect,
    Amount,
    AvoidDamageTypes,
    BowAmmoType,
    BowRange,
    Brightness,
    ChangeTarget,
    CustomAttributes,
    DamageReduction,
    DecayingState,
    DisguiseTarget,
    Elevation,
    Enabled,
    FontSize,
    HouseDoorId,
    Id,
    InformationType,
    KeydoorTarget,
    LeveldoorTarget,
    LightColor,
    MaxLengthOnce,
    Meaning,
    NamedoorTarget,
    Nutrition,
    PoolLiquidType,
    Professions,
    ProtectionDamageTypes,
    QuestdoorTarget,
    RelTeleportDisplacement,
    RelTeleportEffect,
    RuneCharges,
    SavedExpireTime,
    ShieldDefendValue,
    SkillModification,
    SkillNumber,
    String,
    ThrowAttackValue,
    ThrowDefendValue,
    ThrowEffectStrength,
    ThrowFragility,
    ThrowMissile,
    ThrowRange,
    ThrowSpecialEffect,
    TotalUses,
    WandAttackStrength,
    WandAttackVariation,
    WandDamageType,
    WandMissile,
    WandRange,
    WeaponAttackValue,
    WeaponDefendValue,
    WearoutTarget,
    WrittenBy,
    WrittenDate,
    Door,
    Locked,
    Orientation,

    None2 = 254
}