namespace NeoServer.Scripts.LuaJIT.Models;

public enum MagicEffect : ushort
{
    CONST_ME_NONE,

    CONST_ME_DRAWBLOOD = 1,
    CONST_ME_LOSEENERGY = 2,
    CONST_ME_POFF = 3,
    CONST_ME_BLOCKHIT = 4,
    CONST_ME_EXPLOSIONAREA = 5,
    CONST_ME_EXPLOSIONHIT = 6,
    CONST_ME_FIREAREA = 7,
    CONST_ME_YELLOW_RINGS = 8,
    CONST_ME_GREEN_RINGS = 9,
    CONST_ME_HITAREA = 10,
    CONST_ME_TELEPORT = 11,
    CONST_ME_ENERGYHIT = 12,
    CONST_ME_MAGIC_BLUE = 13,
    CONST_ME_MAGIC_RED = 14,
    CONST_ME_MAGIC_GREEN = 15,
    CONST_ME_HITBYFIRE = 16,
    CONST_ME_HITBYPOISON = 17,
    CONST_ME_MORTAREA = 18,
    CONST_ME_SOUND_GREEN = 19,
    CONST_ME_SOUND_RED = 20,
    CONST_ME_POISONAREA = 21,
    CONST_ME_SOUND_YELLOW = 22,
    CONST_ME_SOUND_PURPLE = 23,
    CONST_ME_SOUND_BLUE = 24,
    CONST_ME_SOUND_WHITE = 25,
    CONST_ME_BUBBLES = 26,
    CONST_ME_CRAPS = 27,
    CONST_ME_GIFT_WRAPS = 28,
    CONST_ME_FIREWORK_YELLOW = 29,
    CONST_ME_FIREWORK_RED = 30,
    CONST_ME_FIREWORK_BLUE = 31,
    CONST_ME_STUN = 32,
    CONST_ME_SLEEP = 33,
    CONST_ME_WATERCREATURE = 34,
    CONST_ME_GROUNDSHAKER = 35,
    CONST_ME_HEARTS = 36,
    CONST_ME_FIREATTACK = 37,
    CONST_ME_ENERGYAREA = 38,
    CONST_ME_SMALLCLOUDS = 39,
    CONST_ME_HOLYDAMAGE = 40,
    CONST_ME_BIGCLOUDS = 41,
    CONST_ME_ICEAREA = 42,
    CONST_ME_ICETORNADO = 43,
    CONST_ME_ICEATTACK = 44,
    CONST_ME_STONES = 45,
    CONST_ME_SMALLPLANTS = 46,
    CONST_ME_CARNIPHILA = 47,
    CONST_ME_PURPLEENERGY = 48,
    CONST_ME_YELLOWENERGY = 49,
    CONST_ME_HOLYAREA = 50,
    CONST_ME_BIGPLANTS = 51,
    CONST_ME_CAKE = 52,
    CONST_ME_GIANTICE = 53,
    CONST_ME_WATERSPLASH = 54,
    CONST_ME_PLANTATTACK = 55,
    CONST_ME_TUTORIALARROW = 56,
    CONST_ME_TUTORIALSQUARE = 57,
    CONST_ME_MIRRORHORIZONTAL = 58,
    CONST_ME_MIRRORVERTICAL = 59,
    CONST_ME_SKULLHORIZONTAL = 60,
    CONST_ME_SKULLVERTICAL = 61,
    CONST_ME_ASSASSIN = 62,
    CONST_ME_STEPSHORIZONTAL = 63,
    CONST_ME_BLOODYSTEPS = 64,
    CONST_ME_STEPSVERTICAL = 65,
    CONST_ME_YALAHARIGHOST = 66,
    CONST_ME_BATS = 67,
    CONST_ME_SMOKE = 68,
    CONST_ME_INSECTS = 69,
    CONST_ME_DRAGONHEAD = 70,
    CONST_ME_ORCSHAMAN = 71,
    CONST_ME_ORCSHAMAN_FIRE = 72,
    CONST_ME_THUNDER = 73,
    CONST_ME_FERUMBRAS = 74,
    CONST_ME_CONFETTI_HORIZONTAL = 75,
    CONST_ME_CONFETTI_VERTICAL = 76,

    // 77-157 are empty
    CONST_ME_BLACKSMOKE = 158,

    // 159-166 are empty
    CONST_ME_REDSMOKE = 167,
    CONST_ME_YELLOWSMOKE = 168,
    CONST_ME_GREENSMOKE = 169,
    CONST_ME_PURPLESMOKE = 170,
    CONST_ME_EARLY_THUNDER = 171,
    CONST_ME_RAGIAZ_BONECAPSULE = 172,
    CONST_ME_CRITICAL_DAMAGE = 173,

    // 174 is empty
    CONST_ME_PLUNGING_FISH = 175,
    CONST_ME_BLUE_ENERGY_SPARK = 176,
    CONST_ME_ORANGE_ENERGY_SPARK = 177,
    CONST_ME_GREEN_ENERGY_SPARK = 178,
    CONST_ME_PINK_ENERGY_SPARK = 179,
    CONST_ME_WHITE_ENERGY_SPARK = 180,
    CONST_ME_YELLOW_ENERGY_SPARK = 181,
    CONST_ME_MAGIC_POWDER = 182,

    // 183 is empty
    CONST_ME_PIXIE_EXPLOSION = 184,
    CONST_ME_PIXIE_COMING = 185,
    CONST_ME_PIXIE_GOING = 186,

    // 187 is empty
    CONST_ME_STORM = 188,
    CONST_ME_STONE_STORM = 189,

    // 190 is empty
    CONST_ME_BLUE_GHOST = 191,

    // 192 is empty
    CONST_ME_PINK_VORTEX = 193,
    CONST_ME_TREASURE_MAP = 194,
    CONST_ME_PINK_BEAM = 195,
    CONST_ME_GREEN_FIREWORKS = 196,
    CONST_ME_ORANGE_FIREWORKS = 197,
    CONST_ME_PINK_FIREWORKS = 198,
    CONST_ME_BLUE_FIREWORKS = 199,

    // 200 is empty
    CONST_ME_SUPREME_CUBE = 201,
    CONST_ME_BLACK_BLOOD = 202,
    CONST_ME_PRISMATIC_SPARK = 203,
    CONST_ME_THAIAN = 204,
    CONST_ME_THAIAN_GHOST = 205,
    CONST_ME_GHOST_SMOKE = 206,

    // 207 is empty
    CONST_ME_WATER_BLOCK_FLOATING = 208,
    CONST_ME_WATER_BLOCK = 209,
    CONST_ME_ROOTS = 210,

    // 211-212 is empty
    CONST_ME_GHOSTLY_SCRATCH = 213,
    CONST_ME_GHOSTLY_BITE = 214,
    CONST_ME_BIG_SCRATCH = 215,
    CONST_ME_SLASH = 216,
    CONST_ME_BITE = 217,

    // 218 empty or debug
    CONST_ME_CHIVALRIOUS_CHALLENGE = 219,
    CONST_ME_DIVINE_DAZZLE = 220,
    CONST_ME_ELECTRICALSPARK = 221,
    CONST_ME_PURPLETELEPORT = 222,
    CONST_ME_REDTELEPORT = 223,
    CONST_ME_ORANGETELEPORT = 224,
    CONST_ME_GREYTELEPORT = 225,
    CONST_ME_LIGHTBLUETELEPORT = 226,

    // 227-229 are empty
    CONST_ME_FATAL = 230,
    CONST_ME_DODGE = 231,
    CONST_ME_HOURGLASS = 232,
    CONST_ME_DAZZLING = 233,
    CONST_ME_SPARKLING = 234,
    CONST_ME_FERUMBRAS_1 = 235,
    CONST_ME_GAZHARAGOTH = 236,
    CONST_ME_MAD_MAGE = 237,
    CONST_ME_HORESTIS = 238,
    CONST_ME_DEVOVORGA = 239,
    CONST_ME_FERUMBRAS_2 = 240,

    CONST_ME_WHITE_SMOKE = 241,
    CONST_ME_WHITE_SMOKES = 242,
    CONST_ME_WATER_DROP = 243,
    CONST_ME_AVATAR_APPEAR = 244,
    CONST_ME_DIVINE_GRENADE = 245, // Permanent
    CONST_ME_DIVINE_EMPOWERMENT = 246, // Permanent
    CONST_ME_WATER_FLOATING_THRASH = 247,

    CONST_ME_AGONY = 249,

    CONST_ME_LOOT_HIGHLIGHT = 252,

    CONST_ME_LAST
}